/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#F0ECE5',
        card: '#FBFBFA',
        surface: {
          DEFAULT: '#FBFBFA',
          elevated: '#FFFFFF',
          subtle: '#EAE6DF',
          muted: '#F5F3EF',
        },
        brand: {
          DEFAULT: '#1D5BB9',
          hover: '#154694',
          light: '#EEF4FD',
          muted: '#C9DCFB',
        },
        stroke: {
          DEFAULT: '#E5E2DC',
          soft: '#E5E2DC',
          faint: 'rgba(28, 28, 26, 0.04)',
        },
        ink: {
          DEFAULT: '#1C1C1A',
          primary: '#1C1C1A',
          secondary: '#54534F',
          muted: '#8D8C86',
          faint: '#B8B6AF',
        },
        line: {
          DEFAULT: '#E5E2DC',
          subtle: '#EAE6DF',
          border: '#E5E2DC',
        },
        hz: {
          bg: '#F0ECE5',
          card: '#FBFBFA',
          brand: '#1D5BB9',
          'brand-hover': '#154694',
          'brand-light': '#EEF4FD',
          'brand-dark': '#0E2D60',
          heading: '#1C1C1A',
          body: '#54534F',
          muted: '#8D8C86',
          border: '#E5E2DC',
          accent: '#1D5BB9',
          'success-light': '#E6F8F1',
          'warning-light': '#EEF4FD',
          'danger-light': '#FEEFEF',
        },
        'hz-brand': '#1D5BB9',
        'hz-brand-hover': '#154694',
        'hz-brand-light': '#EEF4FD',
        'hz-brand-dark': '#0E2D60',
        'hz-bg': '#F0ECE5',
        'hz-card': '#FBFBFA',
        'hz-heading': '#1C1C1A',
        'hz-body': '#54534F',
        'hz-muted': '#8D8C86',
        'hz-border': '#E5E2DC',
        pastel: {
          green: '#E6F8F1',
          'green-text': '#01B574',
          'green-border': '#B7EBCE',
          blue: '#EBF4FF',
          'blue-text': '#2B6CB0',
          'blue-border': '#BEE3F8',
          amber: '#FFF8EC',
          'amber-text': '#D8902A',
          'amber-border': '#FEEBC8',
          rose: '#FEEFEF',
          'rose-text': '#EE5D50',
          'rose-border': '#FED7D7',
        }
      },
      borderRadius: {
        'bento': '28px',
        'bento-sm': '18px',
        'pill': '9999px',
      },
      boxShadow: {
        '2xs': '0 1px 2px 0 rgba(0, 0, 0, 0.03)',
        'xs': '0 1px 3px 0 rgba(0, 0, 0, 0.04), 0 1px 2px -1px rgba(0, 0, 0, 0.04)',
        'subtle': '0 2px 8px 0 rgba(0, 0, 0, 0.03)',
        'soft-card': '0 4px 20px -2px rgba(28, 28, 26, 0.03), 0 1px 3px 0 rgba(28, 28, 26, 0.02)',
        'soft-float': '0 12px 32px -4px rgba(28, 28, 26, 0.06)',
        'pill': '0 2px 8px rgba(28, 28, 26, 0.04)',
        'hz-card': '0 4px 20px -2px rgba(28, 28, 26, 0.03), 0 1px 3px 0 rgba(28, 28, 26, 0.02)',
        'hz-card-sm': '0 2px 8px 0 rgba(28, 28, 26, 0.03)',
        'hz-button': '0px 4px 12px rgba(29, 91, 185, 0.22)',
      },
      fontFamily: {
        sans: ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'SF Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
